aragon/court-dashboard

- src/components/Dashboard/LatestActivity.js
- src/components/Disputes/DisputeCard.js
- src/components/Disputes/DisputeDetail.js
- src/components/Disputes/DisputeEvidences.js
- src/components/Disputes/DisputeInfo.js
- src/components/Disputes/DisputeTimeline.js
- src/mock-data.js
- Added evidences view 
- Also removed the dropdown actions form the dispute card and made the detail view accessible through onClick action.
- Decreased the margin between the `vote` button and the last row at `disputeInfo` component
> Remove dropDown from dispute card and add evidences view

- config-overrides.js
For some reason it wasn’t used by react-app-rewired on my setup, setting it explicitly fixes that.
> react-app-rewired: use the .eslintrc file

- .yarnrc.yml
- yarn.lock
Waiting for copy-aragon-ui-assets to be compatible with PnP.
Also waiting for the next yarn version to be released to get [this fix](https://github.com/yarnpkg/berry/pull/692). Alternatively, we could upgrade react-scripts which has an updated version of fsevents.
> Lock yarn to v1 for now

- src/index.js
closes #90 
Includes connection retry and in the case we reach the maximum number of connection attempts (set to 10) we send an error log to Sentry.
> Graph reconnection attempts

- src/components/Dashboard/Dashboard.js
Since now deactivation requests are processed before activating ANJ, we 
update the max amount allowed for activation from inactive wallet.
> Update max ANJ  amount to active from inactive balance

- src/components/Disputes/DisputeInfo.js
It can happen that a dispute is appealed, but no one confirms the appeal. 
In these cases, the final ruling of the dispute is the ruling the appealer ruled for.
> Check last round appealed to compute final outcome

- .github/workflows/mainnet.yml
- now-mainnet.json
- now.json
- package.json
This adds a Github Action to "manually" deploy a mainnet build via Now on merges to `development`.
We will continue using the Now Github integration to deploy Rinkeby builds from PRs and merges to `development`.
DNS configuration being set up now.
> Add mainnet deployment configuration

- src/components/Disputes/DisputeTimeline.js
Noticed that when a new round is created, the `::after` content for the accordions is displayed and at the bottom of the `<Box />`
This PR hides the line for accordions
> Timeline: Fix UI bug

- src/endpoints.js
The mainnet URL does not have a `-{networkName}` postfix.
> Update mainnet subgraph API URL

- src/hooks/useCourtContracts.js
See https://etherscan.io/tx/0xab402538f9ec655947f405540bcabdbbd3fc004cadfd557872f3ee29484d747c.
The transaction takes 300k gas overall, but because of EIP-150's 63/64th gas rule, the inner call  to "draw" funds from the token into the juror does not receive enough gas to complete.
I've updated this to 500k gas in the meantime, as a safe limit (again, this is why web3 providers do gas estimations on their side 😄).
> Increase gas limit for ANJ activation

- src/components/Disputes/DisputeTimeline.js
Following @bpierre 's advice on setting the width on icons that have text close to them so it doesn't make a weird transition when loading images.
> Timeline: Set icons width

- src/components/Disputes/DisputePhase.js
- src/components/Disputes/DisputeTimeline.js
The `end` prop on `Timer` expects a `Date` instead of a `dayjs` object.
> Timer: Use Date instead of dayjs

- src/networks.js
Changes the Rinkeby court instance based on whether we want the usability environment (fixes `court-rinkeby.aragon.org after merging #132).
A bit hacky, but I don't think we need to get too detailed on how we select this environment since it'll be going away :). In the future it might be nice to have something like [`network-config`](https://github.com/aragon/aragon/blob/master/src/network-config.js) to specify and override values.
> Update Court address based on usability environment

- src/components/Dashboard/Balance.js
> Dashboard: fix help text for locked active tokens

- now-mainnet.json
- public/index.html
- scripts/build.sh
Note: we should also remove the `court-dashboard-fortmatic-site-verification` secret on Now.
> Remove Fortmatic verification meta

- .github/workflows/mainnet.yml
- .gitignore
Now CLI v17 now asks for confirmation the first time a user tries to deploy; using `--confirm` confirms this check automatically on a CI environment.
> now: fix custom mainnet deployment action

- src/components/Dashboard/Balance.js
- src/components/Disputes/actions/DisputeAppeal.js
- src/components/Disputes/actions/DisputeDraft.js
- src/components/Disputes/actions/DisputeExecuteRuling.js
- src/components/Disputes/actions/DisputeReveal.js
- src/components/Disputes/panels/AppealPanel.js
- src/components/Disputes/panels/CommitPanel.js
Noticed that some info sections where not entirely accurate. 
1. Execute ruling info section: Whoever executes the dispute ruling will not get rewards.
Users can earn rewards from executing actions when: 
- Drafting
- Settling penalties
2. When appealing, if the final ruling of a dispute is different from the ruling appealed for, the appealer will lose the entire deposit only if the opposed ruling is the same as  the final ruling. Otherwise, both parties will get their deposits back  `- (round fees )/ 2`.
Fixes #189.
> Appeal: amend info copy

- src/utils/dispute-utils.js
We were calculating evidence submission end time based on dispute creation time which was not correct. 
We also were showing appeal confirmation outcome before the phase actually ended.
> Dispute timeline fixes

- src/utils/crvoting-utils.js
The outcome texts were too long for the timeline and were wrapped in the next line.
Followed [this figma file](https://www.figma.com/file/IdVA6iMn0cWLV5imylwEUP/%E2%9C%85-MASTER-Court-Dashboard?node-id=3783%3A0) to update them.
> Dispute timeline: Amend outcome texts

- src/components/Dashboard/Balance.js
- src/hooks/useTokenBalanceToUsd.js
- src/utils/known-tokens.js
See https://github.com/aragon/court-dashboard/pull/219#discussion_r387924367
For other tokens we can directly use the `cryptocompare` api price info.
Also made `known-tokens` generic.
> Use cryptocompare api for non ANJ tokens

- src/components/Activity/activity-types.js
- src/components/Dashboard/Dashboard.js
- src/components/Dashboard/DashboardStateProvider.js
- src/components/Dashboard/RewardsModule.js
- src/dashboard-logic.js
- src/hooks/query-hooks.js
- src/hooks/subscription-hooks.js
- src/hooks/useANJ.js
- src/hooks/useCourtContracts.js
- src/hooks/useJurorSubscriptionFees.js
- src/networks.js
- src/providers/CourtConfig.js
- src/queries/balances.js
- src/queries/court.js
- src/queries/juror.js
- src/utils/court-utils.js
- src/utils/dispute-utils.js
- src/utils/subscription-utils.js
Now that we have available the `subscriptionModule` at the subgraph, we can now drop most of the contract calls (we must still use `getJurorShare`)  and improve performance.
This PR also includes changes on the way we request an account treasury balances and contemplates latest changes made by @facuspagnuolo here https://github.com/aragon/court-subgraph/pull/53
> Refactor: Court subscriptions and treasury balances query

- src/components/Disputes/DisputeCurrentRuling.js
closes #236 
When implementing this, i wondered whether we should also show this hint in the voting phase.
What do you think?
**Preview:**
> Disputes: show juror weight hint for jurors drafted more than once

- src/components/Activity/ActivityProvider.js
We had a minor issue in the activity provider where we weren't handling the cases between when an account that has activities stored, changes to an account which doesn't have any.
> Activity Module: Update account's activities when empty

- src/hooks/useCourtContracts.js
Closes #271 
We won't be using total ANT staked for networks that aren't mainnet.
> `useCourtContracts`: Invalid address fix.

- src/components/Onboarding/OnboardingModal.js
- src/components/OnboardingLoader.js
This leaves `onClose` as `undefined` rather than `null`, which makes `Modal` use its default rather than trying to call `null`.
Also removes the close button since `onClose` is never set.
> Onboarding modal: prevent error when trying to close

- emails/templates/ruled.js
More or less the same as the `drafted` email, just slight text variation.
Depending on the types of notifications we use with the automated service, we may want to make this base "positive infobox" template more generic.
> Email: add ruled notification

- src/components/ClockModule.js
Sometimes, fetching the court data from the subgraph, takes longer than expected.
In this situations, users seem to try to heartbeat the court thinking it could be out of sync.
This PR disables the heartbeat action button if the court configuration has not been fetched and mitigates the issue at https://sentry.io/share/issue/2b43c8bd402f422dbd9b130817ed7d7c/.
> Clock Module: Disable heartbeat action when court has not fully loaded

- src/utils/dispute-utils.js
Noticed that the drafted date was off in the dispute timeline.
- Sets the `endTime` on the draft phase only after it has passed.
**Before:**
**After:**
> DisputeTimeline: Fix drafted date

- src/components/Disputes/panels/RevealPanel.js
- src/hooks/useCourtContracts.js
This PR mitigates the issue at https://sentry.io/organizations/aragon-association/issues/1627622442/?project=2293705
Validates calculated outcome based on commitment and one time code before proceeding to reveal.
> Reveal panel: Validate One Time Code input

- src/components/Account/AccountModule.js
Fixes a bug regarding the Account Module and an uneven number of providers.
**How can this happen?**
Right now, the way we're calculating the height for the popover is adding the header and footer height, and then dynamically calculating the height for the providers depending on how many they are. While it's not shown on the court dashboard as we have an even number of providers, this can be seen as soon as we set an uneven number of them (e.g removing Portis or Fortmatic).
The fix is just to always make the number of providers even so height is always properly calculated.
> AccountModule: Fix providers height bug

- src/components/EmailNotifications/DeleteEmail.js
- Calling this action "irreversible" is inaccurate, and is even contradicted in the next sentence: "You can always re-subscribe from the notifications preferences later."
> Remove "irreversibly" from unsubscribe copy

- src/components/Tasks/TasksTable.js
- src/hooks/subscription-hooks.js
- src/hooks/useTasks.js
- src/utils/dispute-utils.js
closes #319 
- Removes redundant status from task table
- Uses court clock for updating tasks
While removing the redundant status, realized that we forgot to update the usage of the clock by tasks as well when implementing https://github.com/aragon/court-dashboard/pull/338 😅
> Tasks: Use court clock

- src/components/Disputes/DisputeActions.js
- src/components/Disputes/actions/DisputeVoting.js
- src/components/Onboarding/content.js
- "successfuly" -> "successfully"
- Added "and revealed" so that jurors have an explicit acknowledgement that the reveal step worked properly
- Change "majority" to "plurality", because Aragon Court rulings are based on plurality rule, not majority rule.
> Fix typo and clarify wording

- src/components/Account/AccountModule.js
- src/components/Account/ScreenProviders.js
- src/components/Onboarding/Navigation.js
- src/components/Onboarding/OnboardingModal.js
Closes #159, #349.
Also solves a bug in the Onboarding Modal: clicking the Close button (The X) doesn't close the modal.
Screenshots:
- Providers before:
- Providers after (only two providers as I'm running it locally):
- Connection error before:
- Connection error after:
- Connected before:
- Connected after:
(Note that it kinda bugs me that we're using "account now" but we have "Disconnect wallet". It's accurate, but I think we could also change this to "Disconnect account")
> AccountModule: update "provider" copy to move towards wallets and accounts

- docs/CONFIGURATION.md
- now.json
- scripts/build
- src/environment.js
- src/sentry.js
We did this simplification over at the network-dashboard as well.
We don't need to detect the branch any more, since our default `now` target is now staging and we can just disable the sentry dsn there.
> chore: simplify sentry configuration to avoid requiring branch name

- src/hooks/useCourtContracts.js
Switches the total ANT staked to only use the network vault reserves, matching the stats shown in the [network stats site](https://stats.aragon.network/).
> Stats: Use only network reserve ANT

- src/App.js
It turns out it's still impossible to have a consistent routing experience on IPFS (across the general case of all gateways) without using a hash router.
We will be transitioning this frontend to be hosted by Fleek, which allows us to directly leverage IPFS and IPNS.
> Routing: use hash router

- src/components/Dashboard/ANJLockedDistribution.js
- src/components/Dashboard/AppealColateralModule.js
- src/components/Dashboard/RewardsModule.js
- src/components/Tasks/TasksTable.js
From https://reactrouter.com/web/api/HashRouter
It appears that for anchors we need to add the `#` in front of the path.
> Routing: update links for HashRouter

- src/lib/math-utils.js
fixes #390  
When upgrading ethers to v5, forgot to update the `BigNumber` constructor
> Fix BigNumber usage

- src/components/Disputes/DisputeEvidences.js
- src/hooks/useEvidences.js
Since we are now using a polling mechanism, new objects come every 13 seconds. 
This PR prevents `DisputeEvidences` component from re-rendering if there are no new evidences
> Evidences: Prevent accordion from auto-collapsing.

- src/components/Disputes/actions/DisputeExecuteRuling.js
- src/hooks/useCourtContracts.js
- src/types/dispute-status-types.js
Quick frontend update to disable the current set of precedence campaign disputes from being executed, until all of them have finalized.
> Dispute: disable executions
