aragon/court-dashboard

package.json

Used [in the .babelrc](https://github.com/aragon/court-dashboard/blob/development/.babelrc#L15)

Add babel plugin: proposal-class-properties

---

src/abi/CRVoting.json
src/abi/DisputeManager.json
src/components/Disputes/Disputes.js
src/hooks/useCourt.js
src/utils/court-utils.js
src/utils/crvoting-utils.js

Includes the most general dispute actions.
Will do the actual interactions on a separate PR.

Dispute actions

---

src/components/Dashboard/AccountBanner.js
src/components/Dashboard/BalanceModule.js
src/components/Dashboard/DashboardStateProvider.js
src/hooks/subscription-hooks.js
src/hooks/useJurorDraft.js
src/queries/disputes.js

closes #54 
Includes juror drafted state for the account banner in the balance module.
Until we decide whats a reasonable amount of time to show the drafting state, this implementation shows for all the current term the juror has been drafted in.

Balance module: Add drafted state

---

src/components/Disputes/DisputeCurrentRuling.js
src/components/Disputes/DisputeTimeline.js
src/components/Disputes/panels/AppealPanel.js
src/components/Step.js
src/components/Stepper.js
src/types/dispute-status-types.js
src/utils/crvoting-utils.js
src/utils/dispute-utils.js

This PR includes all the outcomes for the timeline
There is a problem for when the appeal is confirmed, the opposedRuling attr is not getting updated

timeline outcomes

---

src/components/Disputes/DisputeList.js

Dispute List: Add Execute Ruling missing filter

---

src/components/Dashboard/AccountBanner.js
src/components/Dashboard/Balance.js
src/components/Dashboard/Welcome.js

I will be adding more things as PRs continue landing

Pre-launch copy changes

---

src/components/Dashboard/Dashboard.js
src/components/Dashboard/Welcome.js
src/components/Disputes/Disputes.js
src/components/Tasks/Tasks.js
src/components/TitleHeader.js

Added the user guide button to all page headers.

Add user guide button to header

---

src/components/Dashboard/Welcome.js

Also set the image size that was missing.

Welcome: add Buy ANJ link

---

src/hooks/useCourtContracts.js

Decreasing gas limit for now, we should figure out how to estimate it or let the provider do it automatically

Decrease gas limit for ANJ actions

---

src/components/Dashboard/panels/ANJForm.js

closes #120 
Also made the amount formatted with commas when input not focused just as it's done in the microsite.

ANJ Form: Replace input when 0

---

src/hooks/useCourtContracts.js

From https://github.com/aragon/court-dashboard/pull/130#discussion_r377639629.

Increase gas limit for ANJ activation through approveAndCall()

---

src/components/Onboarding/content.js

Some small adjustments and adding/updating links.

Onboarding: update copy

---

src/components/Account/Account.js
src/components/Account/ScreenError.js
src/components/Account/ScreenProviders.js

- Explicit “wrong network” error.
- Add a link to “What is an Ethereum provider”.

Account module fixes

---

package.json
src/components/Disputes/DisputeTimeline.js
src/utils/dispute-utils.js

Timeline: Set Timer to 3 max units

---

src/components/Dashboard/AccountBanner.js

This pr is a fix for the loading ring of the banner that was not showing correctly

loading ring fix

---

src/components/Disputes/DisputeRoundPill.js
src/components/Disputes/Disputes.js

Closes notion item https://www.notion.so/9e7e5cd565b44800a79b5640a5f094a8?v=ef5587b7659946cf806ca4414bcef76a&p=aee66ba6ee584275a381aa4a0bef13e8
The problem appeared only for Firefox browser

Set round pill height 20px

---

src/components/Dashboard/AccountBanner.js

Banner fix

---

src/components/Disputes/panels/CommitPanel.js
src/components/Disputes/panels/RevealPanel.js
src/endpoints.js
src/utils/one-time-code-utils.js

Voting: save secret hash to local storage

---

src/components/Account/ScreenConnected.js
src/components/Disputes/DisputeEvidences.js
src/components/Disputes/DisputeInfo.js
src/components/LocalIdentityBadge/LocalIdentityBadge.js
src/components/Tasks/TasksTable.js
src/hooks/useNetwork.js

Identity badge: Set network type

---

src/networks.js

See https://github.com/aragon/aragon-network-deploy/pull/47.
We've spun up a new environment with 30min term times and less "unavailable" initial disputes.

Rinkeby: update usability court address

---

package.json
src/components/Tasks/TaskStatus.js
src/components/Tasks/TasksTable.js
src/hooks/useFilteredTasks.js
src/hooks/useTasks.js

Tasks: Fix task count

---

src/components/Disputes/DisputePhase.js
src/components/Disputes/DisputeTimeline.js
src/hooks/useANJ.js
src/utils/dispute-utils.js

Remove hardcoded constants

---

src/queries/disputes.js
src/utils/dispute-utils.js

closes #183 
We will also need the time when the appeal was confirmed in case it was.
https://github.com/aragon/court-subgraph/issues/39

Timeline: Update appeal end date when appeal created

---

src/queries/balances.js

Remove treasury tokens from balance query

---

src/components/Disputes/DisputeEvidences.js

From https://www.notion.so/9e7e5cd565b44800a79b5640a5f094a8?v=d3b5e76c06634dafa4b7083edbaca881&p=d8c5c1066f52488185e0bac65a9ff362

Fix evidence inner spacing

---

src/queries/balances.js
src/queries/disputes.js

The court graph was now redeployed.

Uncomment attributes from graph query

---

src/components/Dashboard/RewardsModule.js
src/components/Dashboard/panels/ANJForm.js
src/components/Disputes/actions/DisputeDraft.js
src/components/Disputes/actions/DisputeExecuteRuling.js
src/components/Disputes/panels/AppealPanel.js
src/components/Disputes/panels/CommitPanel.js
src/components/Disputes/panels/RevealPanel.js

closes #211 
Once we have an implementation of the `Signerpanel` we can show proper messages in case the tx failed

Sidepanel: Close after tx signed

---

src/components/Dashboard/RewardsModule.js
src/components/Disputes/actions/DisputeDraft.js
src/components/Disputes/actions/DisputeExecuteRuling.js
src/components/Disputes/panels/AppealPanel.js
src/components/Disputes/panels/CommitPanel.js
src/components/Disputes/panels/RevealPanel.js

Memoizing all form submission functions  see https://github.com/aragon/court-dashboard/pull/177#discussion_r387005036

Use useCallback for form submissions

---

src/components/Disputes/DisputeNotFoundError.js
src/dispute-logic.js
src/hooks/useDisputes.js

From https://github.com/aragon/court-dashboard/pull/198#discussion_r387119798

Invalid dispute fixes

---

src/components/Tasks/TaskDueDate.js
src/components/Tasks/TaskStatus.js
src/components/Tasks/TasksTable.js
src/utils/date-utils.js

Tasks: due date fix

---

src/components/Header/Header.js

Header logo fix

---

src/GlobalErrorHandler.js
src/index.js
src/sentry.js

Slims down the logic a bit, and consolidates initialization logic into its own file.

Sentry: update initialization and usage

---

src/components/Dashboard/DashboardStateProvider.js
src/components/Dashboard/RewardsModule.js
src/hooks/query-hooks.js
src/hooks/subscription-hooks.js
src/hooks/useANJ.js
src/queries/balances.js

This PR includes the changes needed to support [45](https://github.com/aragon/court-subgraph/pull/45)

subgraph: update attributes and code for breaking changes

---

.github/workflows/ropsten.yml
now-ropsten.json

environments: ropsten deployment configuration

---

src/components/Dashboard/AccountBanner.js
src/components/Dashboard/AccountBannerInfo.js
src/components/Dashboard/Balance.js
src/components/Dashboard/Profile.js

At some point the Account Profile and Banner got miss-aligned.
Fixing that in this PR. 
Also added the same fade effect that we use in the `<Balance />` component to the `<AccountBanner />` component

Balance module: Align account banner and profile

---

src/components/Disputes/DisputeEvidences.js
src/components/Disputes/DisputeInfo.js
src/components/Disputes/DisputeOutcomeText.js
src/components/Disputes/actions/DisputeVoting.js
src/hooks/useDisputes.js
src/lib/ipfs-utils.js
src/utils/crvoting-utils.js

This PR includes all the change needed for the precedence campaign restart for the dispute detail component and the timeline.
This closes #260

Dispute: detail component changes for precedence campaign

---

src/components/Dashboard/NoRewards.js
src/hooks/query-hooks.js

Hook rename

---

src/hooks/useTasks.js

Task Table: Fix pagination reset 

---

src/components/Disputes/DisputeTimeline.js
src/utils/date-utils.js

Prefer ISO date formats

---

src/components/Tasks/TaskDueDate.js
src/components/Tasks/TaskStatus.js

We were doing a bad calculation about the `Due:` date and also adjusted the timer units depending on the remaining time

Tasks: Due date calculation and timer

---

src/components/MainView.js

MainView: TOS footer text

---

src/components/Disputes/DisputeDetail.js
src/components/Disputes/panels/CommitPanel.js
yarn.lock

Small updates for code formatting :).

Dispute: cosmetic code update for copy components

---

src/components/Disputes/panels/CommitPanel.js

Reverts aragon/court-dashboard#289

Autoreveal: re-enable

---

src/components/GlobalPreferences/GlobalPreferencesButton.js

Settings: FAQ button

---

.github/workflows/rinkeby.yml
now-rinkeby.json
now-usability.json

- Updates `usability` configuration to point to https://court-usability.aragon.org/dashboard
- Adds `rinkeby` configuration that points to https://court-rinkeby.aragon.org/dashboard

Add new Rinkeby instance

---

src/components/Disputes/DisputeInfo.js

Dispute description: Inline identity badges

---

emails/templates/due-tasks.js

Rewords some of the copy and interpolation since mustachio can't handle string interpolation based on list length.
Also rewords "today" to "soon"; we don't know when these users will receive this email or what timezone they're in... so it's hard to say "today" or "tomorrow".

Emails: adjust due-task for single tasks

---

README.md
docs/CONFIGURATION.md

A few cosmetic rewordings / etc. for the README and configuration options.
**I'm pretty sure we should also update the `docs/metadata.md` file, since we've updated the format for the latest disputes.**

docs: update README.md

---

src/components/GlobalPreferences/Notifications/NotificationsPreferences.js

Needs previous pr's because of the asset.

Notifications: Global preferences

---

package.json
src/components/ClockModule.js
yarn.lock

Uses new `showIcon` prop for the Timer component

Clock Module: Use new prop for Timer

---

src/components/GlobalPreferences/Notifications/VerifyEmailAddressPreferences.js

Notifications: Verify email screen from preferences

---

docs/metadata.md

Considers new expected structure for most recent disputes.

Metadata docs: Update expected structure

---

src/components/Disputes/DisputeActions.js
src/radspec.js

- Fixes typos:  
- mayority -> majority  
- ANJ -> DAI  
- Updates `leak` action radspec description to be more accurate.

Update dashboard wording

---

src/components/Dashboard/NoRewards.js
src/components/Disputes/DisputeDetail.js
src/components/Disputes/DisputeList.js
src/components/Disputes/DisputeNotFoundError.js
src/components/Disputes/NoFilterResults.js
src/components/Errors/GenericError.js
src/components/Tasks/NoMyTasks.js
src/components/Tasks/TasksTable.js

My Tasks: Copy change  and punctuation on info screens

---

src/components/EmailNotifications/EmailNotificationsForm.js
src/components/EmailNotifications/EmailNotificationsManager.js
src/components/EmailNotifications/ExistingEmailSubscription.js
src/components/EmailNotifications/StatusInfo.js
src/components/EmailNotifications/actions.js
src/components/EmailNotifications/constants.js
src/components/GlobalPreferences/GlobalPreferences.js
src/components/GlobalPreferences/Notifications/NotificationsManager.js
src/components/GlobalPreferences/Notifications/UnlockNotifications.js
src/components/GlobalPreferences/Notifications/VerifyEmailAddressPreferences.js

Notifications: Modifications requested by Jhon

---

.github/workflows/ci.yml
.github/workflows/mainnet.yml
.github/workflows/rinkeby.yml
.github/workflows/ropsten.yml
README.md
public/index.html
scripts/build

Finalizes the migration to `master` instead of `development :).

chore: migrate to master, remove development branch

---

src/components/Account/ScreenConnecting.js
src/ethereum-providers/index.js

Updates a few areas missed in #358.

Account: move more instances of 'Ethereum provider' to wallet terminology

---

package.json
src/App.js

Fixes https://github.com/aragon/court-dashboard/issues/388.

chore: use relative asset paths

---

src/components/Disputes/DisputeInfoContent.js
src/hooks/useDisputes.js

Just a few quick things I noticed :).

Dispute: polish URI resolution

---

src/components/Disputes/actions/DisputeExecuteRuling.js
src/hooks/useCourtContracts.js
src/types/dispute-status-types.js

This reverts commit 10f9caafe0fe40d4f439f7718a88921a3d46232e.

Revert "Dispute: disable executions (#397)"

---

src/components/Disputes/DisputeInfoContent.js

Dispute Info: Separate final outcome from disputed action field
